controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.logout:
    path: /logout

# app.panier.index:
#     path: /panier/{id}
#     controller: App\Controller\Frontend\PanierController::addToPanier
#     methods: [GET, POST]
